dataset:
  name: imagenet

autoaug:
  model:
    type: resnet200
  loader:
    aug: fa_reduced_imagenet
    cutout: 0
    batch: 256
    epochs: 270
  lr_schedule:
    type: 'resnet'
    warmup:
      multiplier: 2
      epochs: 3
  optimizer:
    type: sgd
    lr: 0.05
    nesterov: True
    decay: 0.0001
    clip: 0
