autoaug:
  model:
    type: shakeshake26_2x112d
  loader:
    aug: fa_reduced_cifar10
    cutout: 16
    batch: 512
    epochs: 1800
  lr_schedule:
    type: 'cosine'
    warmup:
      multiplier: 4
      epochs: 5
  optimizer:
    type: sgd
    lr: 0.01
    nesterov: True
    decay: 0.002
