apiVersion: apps/v1
kind: Deployment
metadata:
  name: snpe-quantizer
  namespace: snpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snpe-quantizer
  template:
    metadata:
      labels:
        app: snpe-quantizer
    spec:
      affinity:
        # See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#more-practical-use-cases
        # The quantizer is processor intensive, so we do not want more than one per node.
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - snpe-quantizer
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: snpe-quantizer
        image: snpecontainerregistry001.azurecr.io/quantizer:1.0
        resources:
          limits:
            cpu: 4
        env:
        - name: MODEL_STORAGE_CONNECTION_STRING
          value: $MSCS$

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: snpe-quantizer
  namespace: snpe
spec:
  maxReplicas: 100 # define max replica count
  minReplicas: 1   # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snpe-quantizer
  targetCPUUtilizationPercentage: 40 # target CPU utilization