search:
  search_space:
    name: hgnet

    params:
      num_classes: 18
      img_size: [256, 256] # (w, h)
      in_channels: 3
      op_subset: ['conv3x3', 'conv5x5', 'conv7x7']
      stem_strides: [2]

      # Number of downsampling blocks (without counting stem conv)
      num_blocks: 5

      # Maximum number of layers in downsampling blocks
      downsample_block_max_ops: 4

      # Maximum number of layers in skip blocks
      skip_block_max_ops: 2

      # Maximum number of layers in upsampling blocks
      upsample_block_max_ops: 4

      # Maximum number of layers after the final upsampling layer
      post_upsample_max_ops: 2

  algorithm:
    name: evolution_pareto

    params:
      num_iters: 20
      init_num_models: 20
      mutations_per_parent: 5
      num_crossovers: 6
      max_unseen_population: 20
      num_random_mix: 6

  target:
    name: snp
    metric_key: mean
    max_retries: 15
    retry_interval: 120
    verbose: true
    max_parameters: 5e7

aml:
  connection_str: ${MODEL_STORAGE_CONNECTION_STRING}
  blob_container_name: models
  partition_key: main
  experiment_name: facesynthetics