name: PyPI Builder and Releaser

on:
  push:
    tags:
      - "**"

jobs:
  publish-pypi:
    name: Publishes release candidate to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Pulls the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sets up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Installs pypa/build
        shell: bash -l {0}
        run: |
          python -m pip install build --user
      - name: Builds the wheel
        shell: bash -l {0}
        run: |
          python -m build --sdist --wheel --outdir dist/ .
      - name: Publishes to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
