name: Documentation Builder and Publisher

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  build-publish:
    name: Builds and publishes a Sphinx-based documentation
    runs-on: ubuntu-latest
    steps:
      - name: Pulls the repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          fetch-depth: 0
      - name: Sets up Conda with Python 3.8
        uses: conda-incubator/setup-miniconda@9f54435e0e72c53962ee863144e47a4b094bfd35 # v2.3.0
        with:
          python-version: 3.8
          activate-environment: archai
      - name: Installs the requirements
        shell: bash -l {0}
        run: |
          sudo apt install pandoc -y
          python -m pip install --user -e .[dev]
      - name: Builds the documentation
        shell: bash -l {0}
        run: |
          cd docs
          make clean
          make html
      - name: Pushes to gh-pages branch
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
