name: DevSkim Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-devskim:
    name: Checks and analyzes with DevSkim
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Pulls the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Runs DevSkim
        uses: microsoft/devskim-action@4b5047945a44163b94642a1cecc0d93a3f428cc6 # v1.0.16
        with:
          should-scan-archives: false
          output-filename: devskim-results.sarif
      - name: Uploads scanning results
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        with:
          sarif_file: devskim-results.sarif