name: Notebook Tests Runner

on:
  push:
    branches:
      - main
    paths:
      - "archai/**"
      - "docs/getting_started/notebooks/**"
  pull_request:
    branches:
      - main
    paths:
      - "archai/**"
      - "docs/getting_started/notebooks/**"

jobs:
  run-tests:
    name: Run notebook tests with `nbval`
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Pulls the repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          fetch-depth: 0
      - name: Sets up Python ${{ matrix.python-version }}
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installs the requirements
        shell: bash -l {0}
        run: |
          sudo apt install -y graphviz
          python -m pip install --user -e .[dev]
          python -m pip install graphviz
      - name: Runs notebooks tests
        shell: bash -l {0}
        run: |
          pytest --nbval-lax docs/getting_started/notebooks
